<?php
/**
 * TL_ROOT/system/modules/googleplus1/languages/ja/default.php 
 * 
 * Contao extension: googleplus1 2.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2013 Andreas Koob 
 * License   : LGPL 
 * Author    : Andreas Koob (Bandyt) 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['googleplus1'] = "Google+1";
$GLOBALS['TL_LANG']['CTE']['googleplus1button']['0'] = "Google+1のボタン";
$GLOBALS['TL_LANG']['CTE']['googleplus1button']['1'] = "Google+1のボタンをページに追加します。";
$GLOBALS['TL_LANG']['CTE']['googleplus1share']['0'] = "Google+1の共有ボタン";
$GLOBALS['TL_LANG']['CTE']['googleplus1share']['1'] = "Google+1の共有ボタンをページに追加します。";
$GLOBALS['TL_LANG']['googleplus1']['share'] = "Google+で共有";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['ar'] = "アラビア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['bg'] = "ブルガリア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['ca'] = "カタルーニャ語、バレンシア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['zh-CN'] = "中国語(簡体字)";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['zh-TW'] = "中国語(繁体字)";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['hr'] = "クロアチア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['cs'] = "チェコ語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['da'] = "デンマーク語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['nl'] = "オランダ語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['en-GB'] = "英語(英国)";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['en-US'] = "英語(アメリカ合衆国)";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['et'] = "エストニア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['fil'] = "フィリピン語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['fi'] = "フィンランド語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['fr'] = "フランス語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['de'] = "ドイツ語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['el'] = "ギリシャ語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['iw'] = "ヘブライ語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['hi'] = "ヒンディー語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['hu'] = "ハンガリー語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['id'] = "インドネシア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['it'] = "イタリア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['ja'] = "日本語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['ko'] = "韓国語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['lv'] = "ラトビア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['lt'] = "リトアニア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['ms'] = "マレー語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['no'] = "ノルウェー語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['fa'] = "ペルシア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['pl'] = "ポーランド語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['pt-BR'] = "ポルトガル語(ブラジル)";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['pt-PT'] = "ポルトガル語(ポルトガル)";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['ro'] = "ルーマニア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['ru'] = "ロシア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['sr'] = "セルビア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['sk'] = "スロバキア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['sl'] = "スロベニア語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['es'] = "スペイン語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['es-419'] = "スペイン語(南アメリカ)";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['sv'] = "スウェーデン語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['th'] = "タイ語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['tr'] = "トルコ語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['uk'] = "ウクライナ語";
$GLOBALS['TL_LANG']['googleplusone_language']['reference']['vi'] = "ベトナム語";
 
?>
