<?php
/**
 * TL_ROOT/system/modules/googleplus1/languages/ja/modules.php 
 * 
 * Contao extension: googleplus1 2.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2013 Andreas Koob 
 * License   : LGPL 
 * Author    : Andreas Koob (Bandyt) 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['googleplus1'] = "Google+1";
$GLOBALS['TL_LANG']['FMD']['mod_googleplus1button']['0'] = "Google+1のボタン";
$GLOBALS['TL_LANG']['FMD']['mod_googleplus1button']['1'] = "Google+1のボタンをページに追加します。";
$GLOBALS['TL_LANG']['FMD']['mod_googleplus1share']['0'] = "Google+1の共有ボタン";
$GLOBALS['TL_LANG']['FMD']['mod_googleplus1share']['1'] = "Google+1の共有ボタンをページに追加します。";
 
?>
