<?php
/**
 * TL_ROOT/system/modules/googleplus1/languages/ja/tl_content.php 
 * 
 * Contao extension: googleplus1 2.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2013 Andreas Koob 
 * License   : LGPL 
 * Author    : Andreas Koob (Bandyt) 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['googleplus1_settings'] = "Google+1の設定";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_count']['0'] = "カウンター";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_count']['1'] = "カウンターを表示したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_differenthref']['0'] = "異なるアドレス";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_differenthref']['1'] = "現在と異なるアドレスを使用したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_href']['0'] = "アドレス";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_href']['1'] = "このボタンで参照するアドレスです。";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_size']['0'] = "大きさ";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_size']['1'] = "ボタンの大きさ";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_size']['reference']['s'] = "小";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_size']['reference']['m'] = "中";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_size']['reference']['l'] = "高";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_size']['reference']['d'] = "標準";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_loading']['0'] = "Javascriptの読み込み";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_loading']['1'] = "GoogleからJavascriptを読み込む方式です。";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_loading']['reference']['a'] = "非同期";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_loading']['reference']['s'] = "同期";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_language']['0'] = "Google+1の言語";
$GLOBALS['TL_LANG']['tl_content']['googleplusone_language']['1'] = "Google+1のボタンの言語を指定します。";
 
?>
