<?php
/**
 * TL_ROOT/system/modules/adsense/languages/it/modules.php 
 * 
 * Contao extension: adsense 1.1.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2011 Andreas Koob 
 * License   : LGPL 
 * Author    : Andreas Koob (Bandyt) 
 * Translator: Andrea Bizioli (Abisem) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['googleadsense'] = "Google AdSense";
$GLOBALS['TL_LANG']['FMD']['adsense']['0'] = "Google AdSense";
$GLOBALS['TL_LANG']['FMD']['adsense']['1'] = "Codice annuncio richiesto per Google AdSense nella tua pagina.";
 
?>
