<?php
/**
 * TL_ROOT/system/modules/adsense/languages/it/tl_module.php 
 * 
 * Contao extension: adsense 1.1.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2011 Andreas Koob 
 * License   : LGPL 
 * Author    : Andreas Koob (Bandyt) 
 * Translator: Andrea Bizioli (Abisem) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['adsense_settings'] = "Impostazioni AdSense";
$GLOBALS['TL_LANG']['tl_module']['adsense_clientid']['0'] = "Publisher-Id";
$GLOBALS['TL_LANG']['tl_module']['adsense_clientid']['1'] = "Il tuo AdSense publisher id. Puoi trovarlo nell'angolo detro in alto in Google Adsense.";
$GLOBALS['TL_LANG']['tl_module']['adsense_adslot']['0'] = "Id annuncio";
$GLOBALS['TL_LANG']['tl_module']['adsense_adslot']['1'] = "Id dell'annuncio da mostrare. Può essere trovato nelle impostazioni dell'annuncio.";
$GLOBALS['TL_LANG']['tl_module']['adsense_width']['0'] = "Larghezza";
$GLOBALS['TL_LANG']['tl_module']['adsense_width']['1'] = "Larghezza dell'elemento AdSense.";
$GLOBALS['TL_LANG']['tl_module']['adsense_height']['0'] = "Altezza";
$GLOBALS['TL_LANG']['tl_module']['adsense_height']['1'] = "Altezza dell'elemento AdSense.";
 
?>
